
'use strict';
const VIEW=document.body.dataset.view||'crm';
const KEY='scout-crm-v1', STAGES=['New','Researching','Contacted','Meeting booked','Proposal sent','Won','Lost'];
const $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeUrl=v=>{try{const u=new URL(v);return ['http:','https:'].includes(u.protocol)?u.href:''}catch{return ''}};
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const keyFor=r=>{let d=r.domain||'';try{d=d||new URL(r.website||r.website_url).hostname}catch{}return d?`domain:${d.toLowerCase().replace(/^www\./,'')}`:`company:${String(r.company||'').trim().toLowerCase()}`};
let saved={},records=[],visible=[],editing=null,storageOK=true;
function message(t){$('status').textContent=t}
try{const data=JSON.parse(localStorage.getItem(KEY)||'{}');if(data&&typeof data==='object'&&!Array.isArray(data))saved=data}catch{storageOK=false;message('Saved CRM could not be loaded. Restore a backup before saving new changes.')}
function persist(next){if(!storageOK)throw Error('Storage could not be read safely. Export a backup before changing browsers.');localStorage.setItem(KEY,JSON.stringify(next));saved=next}
function merged(r){const s=saved[r.key]||{};return {...r,...s,key:r.key,qualified:r.qualified,customerStatus:s.customerStatus||'prospect',stage:STAGES.includes(s.stage)?s.stage:'New'}}
const isClient=r=>r.customerStatus==='client'||r.stage==='Won';
const isExcluded=r=>r.verificationStatus==='excluded';
const inView=r=>VIEW==='clients'?isClient(r):VIEW==='leads'?r.qualified&&!isClient(r):VIEW==='prospects'?!r.qualified&&!isClient(r):r.stage!=='New'||!!r.followup||!!r.notes;
function render(){const all=records.map(merged),q=$('search').value.toLowerCase(),f=$('qualification').value,stage=$('stageFilter').value,due=$('dueOnly').checked;visible=all.filter(r=>inView(r)&&(!q||[r.company,r.contact,r.email,r.notes].join(' ').toLowerCase().includes(q))&&(f==='excluded'?isExcluded(r):f==='unavailable'?r.verificationStatus==='source_unavailable':!isExcluded(r)&&(f==='all'||(f==='qualified')===r.qualified))&&(stage==='all'||r.stage===stage)&&(!due||(r.followup&&r.followup<=today()&&!['Won','Lost'].includes(r.stage))));
$('stats').innerHTML=[['Prospects',all.filter(r=>!r.qualified&&!isClient(r)&&!isExcluded(r)).length],['Clients',all.filter(isClient).length],['Public evidence shortlist',all.filter(r=>r.qualified).length],['Follow-ups due',all.filter(r=>r.followup&&r.followup<=today()&&!['Won','Lost'].includes(r.stage)).length],['Excluded',all.filter(isExcluded).length],['Unavailable sources',all.filter(r=>r.verificationStatus==='source_unavailable').length]].map(([l,n])=>`<div class="stat"><strong>${n}</strong>${l}</div>`).join('');
$('rows').innerHTML=visible.length?visible.map(r=>`<tr><td><button class="link" data-key="${esc(r.key)}">${esc(r.company)}</button><small>${esc(r.domain||'Manually added')}</small><small>${esc(r.verificationReason||'Public verification pending')}</small></td><td><span class="badge ${r.qualified?'qualified':''}">${isExcluded(r)?'Excluded':r.qualified?'Public evidence':'Needs verification'}</span></td><td>${esc(r.stage)}</td><td>${esc(r.contact||'—')}<small>${esc(r.email||'')}</small></td><td class="${r.followup&&r.followup<=today()&&!['Won','Lost'].includes(r.stage)?'overdue':''}">${esc(r.followup||'—')}</td><td><button data-key="${esc(r.key)}">Edit</button></td></tr>`).join(''):'<tr><td colspan="6" class="empty">No matching records in this section. Open Prospects to research or track a company.</td></tr>';
$('rows').querySelectorAll('[data-key]').forEach(b=>b.onclick=()=>openEditor(b.dataset.key));
}
function openEditor(key){editing=key;const r=key?merged(records.find(r=>r.key===key)):{stage:VIEW==='crm'?'Researching':'New',customerStatus:VIEW==='clients'?'client':'prospect'};$('editorTitle').textContent=key?'Edit prospect':'Add research prospect';for(const id of ['company','website','stage','followup','contact','role','email','phone','notes','customerStatus'])$(id).value=r[id]||'';const links=[['Company website',r.website],['Discovery source',r.sourceUrl],['Size source',r.sizeSourceUrl],['Levy source',r.levySourceUrl],['Exclusion evidence',r.exclusionSourceUrl],...(r.reviewedSourceUrls||[]).map((u,i)=>['Reviewed page '+(i+1),u])].filter(([,u])=>safeUrl(u));$('evidence').innerHTML=`<strong>${r.qualified?'Public evidence shortlist — confirm current balance and delivery route':'Needs verification'}</strong><p>${esc(r.sizeEvidence||r.employeeRangeScreen||'No verified size evidence recorded.')}</p><p>${esc(r.levyEvidence||'No employer-specific HRD Corp levy evidence recorded.')}</p><p>${esc(r.exclusionEvidence||'')}</p><p>${esc(r.verificationReason||'Verification pending')}${r.evidenceCheckedAt?' · Checked '+esc(r.evidenceCheckedAt):''}</p>${links.map(([l,u])=>`<a href="${esc(safeUrl(u))}" target="_blank" rel="noopener noreferrer">${l}</a>`).join(' · ')}`;$('editor').showModal()}
$('editForm').onsubmit=e=>{e.preventDefault();const values={};for(const id of ['company','website','stage','followup','contact','role','email','phone','notes','customerStatus'])values[id]=$(id).value.trim();if(!values.company){$('company').focus();return}const key=editing||`manual:${crypto.randomUUID()}`;try{persist({...saved,[key]:{...values,manual:!editing||!!saved[key]?.manual,updatedAt:new Date().toISOString()}});if(!editing)records.push({key,company:values.company,qualified:false});$('editor').close();render();message('Saved on this device.')}catch(err){message('Save failed: '+err.message)}};
$('cancel').onclick=()=>$('editor').close();$('add').onclick=()=>openEditor(null);
for(const id of ['search','qualification','stageFilter','dueOnly'])$(id).addEventListener('input',render);
for(const id of ['stage','stageFilter'])STAGES.forEach(s=>{const o=document.createElement('option');o.value=s;o.textContent=s;$(id).append(o)});
function download(name,text,type){const u=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
$('backup').onclick=()=>download(`scout-crm-${today()}.json`,JSON.stringify({version:1,saved,exportedAt:new Date().toISOString()},null,2),'application/json');
$('exportCsv').onclick=()=>{const fields=['company','website','qualified','customerStatus','verificationStatus','verificationReason','stage','contact','role','email','phone','followup','notes'];const cell=v=>'"'+String(v??'').replace(/^[=+@\-\t\r]/,m=>"'"+m).replace(/"/g,'""')+'"';download(`scout-crm-${today()}.csv`,[fields.join(','),...visible.map(r=>fields.map(f=>cell(r[f])).join(','))].join('\r\n'),'text/csv;charset=utf-8')};
$('restore').onclick=()=>$('restoreFile').click();
$('restoreFile').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>5000000)throw Error('Backup is too large.');const data=JSON.parse(await file.text());if(data.version!==1||!data.saved||typeof data.saved!=='object'||Array.isArray(data.saved))throw Error('Not a Scout CRM backup.');const clean={};for(const [key,row] of Object.entries(data.saved)){if(!/^(domain:|company:|manual:)/.test(key)||!row||typeof row!=='object')throw Error('Invalid record.');const r={manual:key.startsWith('manual:')};for(const f of ['company','website','contact','role','email','phone','notes','followup','updatedAt','customerStatus'])if(typeof row[f]==='string')r[f]=row[f].slice(0,20000);r.stage=STAGES.includes(row.stage)?row.stage:'New';clean[key]=r}persist({...saved,...clean});for(const [key,r] of Object.entries(clean))if(r.manual&&!records.some(x=>x.key===key))records.push({key,company:r.company,qualified:false});render();message('Backup restored. Matching records updated; other records retained.')}catch(err){message('Restore failed: '+err.message)}finally{e.target.value=''}};
async function load(){let failures=[];const map=new Map();for(const [path,isLead] of [['../data/prospects.json',false],['../data/leads.json',true]]){try{const resp=await fetch(path,{cache:'no-store'});if(!resp.ok)throw Error(resp.status);const items=await resp.json();if(!Array.isArray(items))throw Error('Invalid data');for(const r of items){if(!r.company)continue;const key=keyFor(r),previous=map.get(key)||{};map.set(key,{...previous,...r,key,website:safeUrl(r.website||r.website_url||previous.website||''),contact:r.contactName||previous.contact||'',role:r.contactRole||previous.role||'',qualified:!!previous.qualified||!!(isLead&&r.priorityTier==='top'&&r.sizeTier==='SME'&&r.levySignal==='confirmed'&&r.sizeEvidence&&r.levyEvidence)})}}catch{failures.push(path)}}records=[...map.values()];for(const [key,r] of Object.entries(saved))if(r.manual&&!map.has(key))records.push({key,company:r.company,qualified:false});render();message(failures.length?'Some source data could not load. Showing available records; try refreshing.':`${records.length} records loaded. CRM edits stay on this device.`)}
load();

document.querySelectorAll('[data-nav]').forEach(a=>{if(a.dataset.nav===VIEW){a.setAttribute('aria-current','page');a.style.background='#d5e8d9'}});
